name: "MoJ Cloud Platform Authentication Action"
description: "Authenticate with MoJ Cloud Platform Kubernetes namespace"
branding:
  icon: 'anchor'
  color: 'blue'
outputs:
  aws_access_key_id:
    description: "AWS access key ID"
  aws_secret_access_key_id:
    description: "AWS secret access key ID"
  ecr_repo_url:
    description: "AWS ECR Repo URL"
  result:
    description: "Output of the kubectl command run"
runs:
  using: "docker"
  image: "Dockerfile"
